[package]
name = "workenv-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
jsonschema.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
workenv-platform.workspace = true
workenv-protocol.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
